package a.com.me.obo.greendaooldversion;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import a.com.me.obo.greendaooldversion.Note;
import a.com.me.obo.greendaooldversion.ImpressionEntity;

import a.com.me.obo.greendaooldversion.NoteDao;
import a.com.me.obo.greendaooldversion.ImpressionEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig impressionEntityDaoConfig;

    private final NoteDao noteDao;
    private final ImpressionEntityDao impressionEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        impressionEntityDaoConfig = daoConfigMap.get(ImpressionEntityDao.class).clone();
        impressionEntityDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        impressionEntityDao = new ImpressionEntityDao(impressionEntityDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(ImpressionEntity.class, impressionEntityDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        impressionEntityDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public ImpressionEntityDao getImpressionEntityDao() {
        return impressionEntityDao;
    }

}
