package a.com.me.obo.greendaooldversion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table IMPRESSION_ENTITY.
 */
public class ImpressionEntity {

    private Long id;
    private Integer adType;
    private String offerId;
    private String md5Name;
    private Integer impression;
    private Integer click;
    private Integer adPostion;
    private String appID;
    private String placementID;
    private String offerName;
    private Long timeLastUpdate;

    public ImpressionEntity() {
    }

    public ImpressionEntity(Long id) {
        this.id = id;
    }

    public ImpressionEntity(Long id, Integer adType, String offerId, String md5Name, Integer impression, Integer click, Integer adPostion, String appID, String placementID, String offerName, Long timeLastUpdate) {
        this.id = id;
        this.adType = adType;
        this.offerId = offerId;
        this.md5Name = md5Name;
        this.impression = impression;
        this.click = click;
        this.adPostion = adPostion;
        this.appID = appID;
        this.placementID = placementID;
        this.offerName = offerName;
        this.timeLastUpdate = timeLastUpdate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAdType() {
        return adType;
    }

    public void setAdType(Integer adType) {
        this.adType = adType;
    }

    public String getOfferId() {
        return offerId;
    }

    public void setOfferId(String offerId) {
        this.offerId = offerId;
    }

    public String getMd5Name() {
        return md5Name;
    }

    public void setMd5Name(String md5Name) {
        this.md5Name = md5Name;
    }

    public Integer getImpression() {
        return impression;
    }

    public void setImpression(Integer impression) {
        this.impression = impression;
    }

    public Integer getClick() {
        return click;
    }

    public void setClick(Integer click) {
        this.click = click;
    }

    public Integer getAdPostion() {
        return adPostion;
    }

    public void setAdPostion(Integer adPostion) {
        this.adPostion = adPostion;
    }

    public String getAppID() {
        return appID;
    }

    public void setAppID(String appID) {
        this.appID = appID;
    }

    public String getPlacementID() {
        return placementID;
    }

    public void setPlacementID(String placementID) {
        this.placementID = placementID;
    }

    public String getOfferName() {
        return offerName;
    }

    public void setOfferName(String offerName) {
        this.offerName = offerName;
    }

    public Long getTimeLastUpdate() {
        return timeLastUpdate;
    }

    public void setTimeLastUpdate(Long timeLastUpdate) {
        this.timeLastUpdate = timeLastUpdate;
    }

}
