/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_obo_androidjnitest_MainActivity */

#ifndef _Included_com_me_obo_androidjnitest_MainActivity
#define _Included_com_me_obo_androidjnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_obo_androidjnitest_MainActivity
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_me_obo_androidjnitest_MainActivity_getInt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
