/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_obo_mydemos_ndk_NdkActivity */

#ifndef _Included_com_obo_mydemos_ndk_NdkActivity
#define _Included_com_obo_mydemos_ndk_NdkActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_obo_mydemos_ndk_NdkActivity
 * Method:    getNDKInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_obo_mydemos_ndk_NdkActivity_getNDKInt
  (JNIEnv *, jobject);

/*
 * Class:     com_obo_mydemos_ndk_NdkActivity
 * Method:    getNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_obo_mydemos_ndk_NdkActivity_getNDKString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
